### ISSUE TITLE
Want to use my favourite shell instead of os's default shell

### ISSUE THREAD

**Issue by GaryFurash** [ryu1kn/vscode-edit-with-shell#1]
Hi. I tried "sed" and it didn't like the command (not recognized as an internal or external command"). Where is it getting these commands from? Can I configure this (e.g., to use GIT bash or Cygwin)

**Comment by ryu1kn** [comment]
Hi. The plugin uses nodejs's `child_process.spawn` and that uses `cmd.exe` on windows by default (cf. [the api doc](https://nodejs.org/docs/v6.5.0/doc/api/child_process.html#child_process_child_process_spawn_command_args_options)). As the plugin doesn't allow you to specify your favourite shell :|

So if you can use `sed` on your CMD, you should be able to use it on vscode, otherwise you need to configure your `%PATH%` accordingly...

**Comment by GaryFurash** [comment]
;-(

**Comment by ryu1kn** [comment]
I've repurposed this issue for enhancing the extension to let us specify our favourite shell instead of OS's default shell.

**Comment by 4mitch** [comment]
Hello! Thank you for usefull ext! It' great! 
But really it could be great to be able to set different shell. Since VS Code itself provide such setting "terminal.integrated.shell.windows" then may be it is possible to reuse this function? 
cmd.exe is no use in Windows :)

**Comment by ryu1kn** [comment]
Sorry for my late response. I was on holiday :p

Yeah, I think it's reasonable to assume that people want to use the same shell on the integrated terminal and this extension. Thanks for the pointer.

**Comment by ryu1kn** [comment]
Sorry for having taken such a long time, but now it's released as v0.3.0!
You can now use bash or other shells on Windows 😉 @GaryFurash @4mitch
