### ISSUE TITLE
Request: option to ignore warnings

### ISSUE THREAD

**Issue by telecasterer** [ryu1kn/vscode-edit-with-shell#12]
Is it possible to add an option to ignore warnings which may be issued on stderr?
The reason I'm asking is that I'm using this extension to run Tcl code through an ancient formatter called frink that almost always produces warnings. The warnings are correctly displayed and can be useful, however the text/file being processed is then left unchanged. It would be nice to have an option to override this and accept the changed text. Thanks.

**Comment by ryu1kn** [comment]
Hi @telecasterer , thanks for the suggestion with the clear background info.

This extension should still update the text if the command is finishing with exit code 0. I wonder if the command is not only writing warnings to stderr but actually finishing with non-0 status. Can you try this to see if that's the case?

```sh
your-frink-command || true
```

**Comment by telecasterer** [comment]
Thanks for the quick response. Yes, the command is finishing with non-zero exit code.  I can enter the command at the prompt as you kindly suggested "frink || true" and all is well. I can even recall the command and it works as expected.  
I've now run across another issue however. I'm not sure it's related. If I then try to run a different command, for example "sort", then the command prompt doesn't accept it, i.e. I can press enter but nothing happens. I have to press escape to get out of the prompt.

**Comment by ryu1kn** [comment]
Glad to hear that you can now successfully run frink.

I guess the other question is not related to exit code. When you encounter this, can you delete all text in the box, in this case `sort`, and check the placeholder message displayed with grey colour? I guess it will be saying `Select a command to reuse or Cancel (ESC) to write a new command`. If so, just press `ESC` then you'll get a new input box where you can issue `sort`.

The message is different when you invoke the command first time (no history) and the second time afterwards (with history). I don't particularly like this flow but when I introduced the command history feature, because of the available API, I went with this way.

**Comment by telecasterer** [comment]
Thanks
